spring.application.name=my-blog-back-app
server.port=8080

spring.datasource.url=jdbc:h2:mem:usersdb
spring.datasource.username=sa
spring.datasource.password=
upload.dir=uploads/

spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration